In [1]:
import numpy as np
import pandas as pd

In [2]:
np.__version__ # Q1

'1.20.3'

In [3]:
pd.__version__ # Q2

'1.3.2'

In [5]:
import os
import sys
os.getcwd()

'/Users/deepa/dev/ml_zoomcamp/lesson1'

In [7]:
columns = [
    'Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Driven_Wheels', 'Number of Doors' , 'Market Category' ,'Vehicle Size' ,'Vehicle Style', 'highway MPG','city mpg','Popularity','MSRP'
]
df = pd.read_csv("/Users/deepa/dev/ml_zoomcamp/lesson1/cars.csv",names=columns)

In [13]:
df.shape # Q3


(11915, 16)

In [15]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  Make       Model  Year             Engine Fuel Type  Engine HP   
1   BMW  1 Series M  2011  premium unleaded (required)        335   
2   BMW    1 Series  2011  premium unleaded (required)        300   
3   BMW    1 Series  2011  premium unleaded (required)        300   
4   BMW    1 Series  2011  premium unleaded (required)        230   

   Engine Cylinders  Transmission Type     Driven_Wheels  Number of Doors  \
0  Engine Cylinders  Transmission Type     Driven_Wheels  Number of Doors   
1                 6             MANUAL  rear wheel drive                2   
2                 6             MANUAL  rear wheel drive                2   
3                 6             MANUAL  rear wheel drive                2   
4                 6             MANUAL  rear wheel drive                2   

                         Market Category  Vehicle Size  Vehicle Style  \
0                        Market Category  Vehicle Size  Vehicle Style   
1  Factory Tuner,Luxury,High-Performance       Compact          Coupe   
2                     Luxury,Performance       Compact    Convertible   
3                Luxury,High-Performance       Compact          Coupe   
4                     Luxury,Performance       Compact          Coupe   

   highway MPG  city mpg  Popularity   MSRP  
0  highway MPG  city mpg  Popularity   MSRP  
1           26        19        3916  46135  
2           28        19        3916  40650  
3           28        20        3916  36350  
4           28        18        3916  29450

In [16]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [22]:
df.dtypes

Make                 object
Model                object
Year                 object
Engine Fuel Type     object
Engine HP            object
Engine Cylinders     object
Transmission Type    object
Driven_Wheels        object
Number of Doors      object
Market Category      object
Vehicle Size         object
Vehicle Style        object
highway MPG          object
city mpg             object
Popularity           object
MSRP                 object
dtype: object

In [32]:
df['MSRP'].dtypes


dtype('O')

In [33]:
df['MSRP'] = df['MSRP'].astype(str)

In [34]:
df['MSRP'].dtypes

dtype('O')

In [38]:
df.iloc[5816]

Make                                Chevrolet
Model                          Impala Limited
Year                                     2014
Engine Fuel Type     flex-fuel (unleaded/E85)
Engine HP                                 300
Engine Cylinders                            6
Transmission Type                   AUTOMATIC
Driven_Wheels               front wheel drive
Number of Doors                             4
Market Category                     Flex Fuel
Vehicle Size                            Large
Vehicle Style                           Sedan
highway MPG                                30
city mpg                                   18
Popularity                               1385
MSRP                                    25830
Name: 5816, dtype: object

In [42]:
df = pd.read_csv("/Users/deepa/dev/ml_zoomcamp/lesson1/cars.csv",names=columns)

In [47]:
df['MSRP'] = df['MSRP'].astype(float)

ValueError: could not convert string to float: 'MSRP'

In [49]:
df['MSRP'] = pd.to_numeric(df['MSRP'].str.replace(",", ""), errors='coerce')

In [50]:
df['MSRP'] = df['MSRP'].astype(float)

In [57]:
cars_2015_df = df[df['Year'] >= '2015']

In [60]:
cars_2015_df['Engine HP'].isnull().sum() # sum of cars with Engine HP null and Year >= 2015

51

In [62]:
df['Engine HP'].isnull().sum()

69

In [65]:
df['Engine HP'].mean()

TypeError: can only concatenate str (not "int") to str

In [66]:
df['Engine HP'] = df['Engine HP'].fillna(0)

In [69]:
df['Engine HP'] = pd.to_numeric(df['Engine HP'].str.replace(",", ""), errors='coerce')
df['Engine HP'] = df['Engine HP'].astype(float)


In [76]:
mean_hp_before = df['Engine HP'].mean()

In [77]:
df['Engine HP'] = df['Engine HP'].fillna(mean_hp_before)

In [73]:
mean_hp_after = df['Engine HP'].mean()

In [74]:
mean_hp_after

249.38607007176

In [78]:
df['Engine HP'] = df['Engine HP'].fillna(0)

In [79]:
df['Engine HP'].mean()

249.38607007176

In [80]:
df = pd.read_csv("/Users/deepa/dev/ml_zoomcamp/lesson1/cars.csv",names=columns)

In [81]:
df['Engine HP'].mean()

TypeError: can only concatenate str (not "int") to str

In [83]:
df['Engine HP'] = df['Engine HP'].fillna(np.nan)

In [85]:
df['Engine HP'] = pd.to_numeric(df['Engine HP'].str.replace(",", ""), errors='coerce')
mean_hp_before = df['Engine HP'].mean()

In [86]:
mean_hp_before

249.38607007176023

In [87]:
df['Engine HP'] = df['Engine HP'].fillna(mean_hp_before)
mean_hp_after = df['Engine HP'].mean()

In [88]:
print(round(mean_hp_before)) # no change
print(round(mean_hp_after))

249
249


In [89]:
df.head()


Make       Model  Year             Engine Fuel Type  Engine HP  \
0  Make       Model  Year             Engine Fuel Type  249.38607   
1   BMW  1 Series M  2011  premium unleaded (required)  335.00000   
2   BMW    1 Series  2011  premium unleaded (required)  300.00000   
3   BMW    1 Series  2011  premium unleaded (required)  300.00000   
4   BMW    1 Series  2011  premium unleaded (required)  230.00000   

   Engine Cylinders  Transmission Type     Driven_Wheels  Number of Doors  \
0  Engine Cylinders  Transmission Type     Driven_Wheels  Number of Doors   
1                 6             MANUAL  rear wheel drive                2   
2                 6             MANUAL  rear wheel drive                2   
3                 6             MANUAL  rear wheel drive                2   
4                 6             MANUAL  rear wheel drive                2   

                         Market Category  Vehicle Size  Vehicle Style  \
0                        Market Category  Vehicle Size  Vehicle Style   
1  Factory Tuner,Luxury,High-Performance       Compact          Coupe   
2                     Luxury,Performance       Compact    Convertible   
3                Luxury,High-Performance       Compact          Coupe   
4                     Luxury,Performance       Compact          Coupe   

   highway MPG  city mpg  Popularity   MSRP  
0  highway MPG  city mpg  Popularity   MSRP  
1           26        19        3916  46135  
2           28        19        3916  40650  
3           28        20        3916  36350  
4           28        18        3916  29450

In [91]:
df_rolls_royce = df[df['Make'] == 'Rolls-Royce']

In [92]:
df_rolls_royce

Make                   Model  Year             Engine Fuel Type  \
2922   Rolls-Royce                Corniche  2001  premium unleaded (required)   
3506   Rolls-Royce                    Dawn  2016  premium unleaded (required)   
5276   Rolls-Royce         Ghost Series II  2015  premium unleaded (required)   
5277   Rolls-Royce         Ghost Series II  2015  premium unleaded (required)   
5278   Rolls-Royce         Ghost Series II  2016  premium unleaded (required)   
5279   Rolls-Royce         Ghost Series II  2016  premium unleaded (required)   
5280   Rolls-Royce                   Ghost  2012  premium unleaded (required)   
5281   Rolls-Royce                   Ghost  2012  premium unleaded (required)   
5282   Rolls-Royce                   Ghost  2013  premium unleaded (required)   
5283   Rolls-Royce                   Ghost  2013  premium unleaded (required)   
5284   Rolls-Royce                   Ghost  2014  premium unleaded (required)   
5285   Rolls-Royce                   Ghost  2014  premium unleaded (required)   
7444   Rolls-Royce               Park Ward  2001  premium unleaded (required)   
7445   Rolls-Royce               Park Ward  2002  premium unleaded (required)   
7554   Rolls-Royce           Phantom Coupe  2014  premium unleaded (required)   
7555   Rolls-Royce           Phantom Coupe  2015  premium unleaded (required)   
7556   Rolls-Royce           Phantom Coupe  2016  premium unleaded (required)   
7557   Rolls-Royce  Phantom Drophead Coupe  2014  premium unleaded (required)   
7558   Rolls-Royce  Phantom Drophead Coupe  2015  premium unleaded (required)   
7559   Rolls-Royce  Phantom Drophead Coupe  2016  premium unleaded (required)   
7560   Rolls-Royce                 Phantom  2014  premium unleaded (required)   
7561   Rolls-Royce                 Phantom  2014  premium unleaded (required)   
7562   Rolls-Royce                 Phantom  2015  premium unleaded (required)   
7563   Rolls-Royce                 Phantom  2015  premium unleaded (required)   
7564   Rolls-Royce                 Phantom  2016  premium unleaded (required)   
7565   Rolls-Royce                 Phantom  2016  premium unleaded (required)   
9432   Rolls-Royce           Silver Seraph  2001  premium unleaded (required)   
9433   Rolls-Royce           Silver Seraph  2002  premium unleaded (required)   
11449  Rolls-Royce                  Wraith  2014  premium unleaded (required)   
11450  Rolls-Royce                  Wraith  2015  premium unleaded (required)   
11451  Rolls-Royce                  Wraith  2016  premium unleaded (required)   

       Engine HP Engine Cylinders Transmission Type     Driven_Wheels  \
2922       325.0                8         AUTOMATIC  rear wheel drive   
3506       563.0               12         AUTOMATIC  rear wheel drive   
5276       563.0               12         AUTOMATIC  rear wheel drive   
5277       563.0               12         AUTOMATIC  rear wheel drive   
5278       563.0               12         AUTOMATIC  rear wheel drive   
5279       563.0               12         AUTOMATIC  rear wheel drive   
5280       563.0               12         AUTOMATIC  rear wheel drive   
5281       563.0               12         AUTOMATIC  rear wheel drive   
5282       563.0               12         AUTOMATIC  rear wheel drive   
5283       563.0               12         AUTOMATIC  rear wheel drive   
5284       563.0               12         AUTOMATIC  rear wheel drive   
5285       563.0               12         AUTOMATIC  rear wheel drive   
7444       322.0               12         AUTOMATIC  rear wheel drive   
7445       322.0               12         AUTOMATIC  rear wheel drive   
7554       453.0               12         AUTOMATIC  rear wheel drive   
7555       453.0               12         AUTOMATIC  rear wheel drive   
7556       453.0               12         AUTOMATIC  rear wheel drive   
7557       453.0               12         AUTOMATIC  rear wheel drive   
7558       453.0               12 

In [94]:
df_rolls_royce_1 = df_rolls_royce[['Engine HP','Engine Cylinders','highway MPG']]

In [95]:
df_rolls_royce_1.head()

Engine HP Engine Cylinders highway MPG
2922      325.0                8          15
3506      563.0               12          19
5276      563.0               12          21
5277      563.0               12          21
5278      563.0               12          21

In [96]:
df_rolls_royce_1 = df_rolls_royce_1.drop_duplicates()

In [98]:
df_rolls_royce_1.shape

(7, 3)

In [99]:
X = df_rolls_royce_1.values
X

array([[325.0, '8', '15'],
       [563.0, '12', '19'],
       [563.0, '12', '21'],
       [563.0, '12', '20'],
       [322.0, '12', '15'],
       [453.0, '12', '19'],
       [624.0, '12', '21']], dtype=object)

In [100]:
XTX = X.T.dot(X)

TypeError: can't multiply sequence by non-int of type 'str'

In [101]:
X_T = X.T

In [102]:
X_T

array([[325.0, 563.0, 563.0, 563.0, 322.0, 453.0, 624.0],
       ['8', '12', '12', '12', '12', '12', '12'],
       ['15', '19', '21', '20', '15', '19', '21']], dtype=object)

In [103]:
XTX = X_T.dot(X)

TypeError: can't multiply sequence by non-int of type 'str'

In [104]:
df_rolls_royce_1['Engine Cylinders'] = pd.to_numeric(df_rolls_royce_1['Engine Cylinders'].str.replace(",", ""), errors='coerce')

In [105]:
df_rolls_royce_1['highway MPG'] = pd.to_numeric(df_rolls_royce_1['highway MPG'].str.replace(",", ""), errors='coerce')

In [106]:
X = df_rolls_royce_1.values
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [107]:
X_T = X.T
X_T

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [108]:
XTX = X_T.dot(X)

In [109]:
XTX_inv = np.linalg.inv(XTX)

In [110]:
XTX_inv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [111]:
XTX_inv.sum() # Q6

0.03221232067748617

In [112]:
y = [1000, 1100, 900, 1200, 1000, 850, 1300]

In [113]:
XTX_XT_TMP = XTX_inv.dot(X_T)

In [114]:
w = XTX_XT_TMP.dot(y) # Q7
w

array([ 0.19989598, 31.02612262, 31.65378877])

In [118]:
df = pd.read_csv("/Users/deepa/dev/ml_zoomcamp/lesson1/cars.csv",names=columns)
bmw_df = df[df['Make'] == 'BMW']
bmw_df

Make       Model  Year             Engine Fuel Type Engine HP  \
1      BMW  1 Series M  2011  premium unleaded (required)       335   
2      BMW    1 Series  2011  premium unleaded (required)       300   
3      BMW    1 Series  2011  premium unleaded (required)       300   
4      BMW    1 Series  2011  premium unleaded (required)       230   
5      BMW    1 Series  2011  premium unleaded (required)       230   
...    ...         ...   ...                          ...       ...   
11902  BMW          Z4  2016  premium unleaded (required)       240   
11903  BMW          Z4  2016  premium unleaded (required)       335   
11904  BMW          Z8  2001  premium unleaded (required)       394   
11905  BMW          Z8  2002  premium unleaded (required)       394   
11906  BMW          Z8  2003  premium unleaded (required)       394   

      Engine Cylinders Transmission Type     Driven_Wheels Number of Doors  \
1                    6            MANUAL  rear wheel drive               2   
2                    6            MANUAL  rear wheel drive               2   
3                    6            MANUAL  rear wheel drive               2   
4                    6            MANUAL  rear wheel drive               2   
5                    6            MANUAL  rear wheel drive               2   
...                ...               ...               ...             ...   
11902                4            MANUAL  rear wheel drive               2   
11903                6  AUTOMATED_MANUAL  rear wheel drive               2   
11904                8            MANUAL  rear wheel drive               2   
11905                8            MANUAL  rear wheel drive               2   
11906                8            MANUAL  rear wheel drive               2   

                             Market Category Vehicle Size Vehicle Style  \
1      Factory Tuner,Luxury,High-Performance      Compact         Coupe   
2                         Luxury,Performance      Compact   Convertible   
3                    Luxury,High-Performance      Compact         Coupe   
4                         Luxury,Performance      Compact         Coupe   
5                                     Luxury      Compact   Convertible   
...                                      ...          ...           ...   
11902                     Luxury,Performance      Compact   Convertible   
11903                Luxury,High-Performance      Compact   Convertible   
11904         Exotic,Luxury,High-Performance      Compact   Convertible   
11905         Exotic,Luxury,High-Performance      Compact   Convertible   
11906         Exotic,Luxury,High-Performance      Compact   Convertible   

      highway MPG city mpg Popularity    MSRP  
1              26       19       3916   46135  
2              28       19       3916   40650  
3              28       20       3916   36350  
4              28       18       3916   29450  
5              28       18       3916   34500  
...           ...      ...        ...     ...  
11902          34       22       3916   49700  
11903          24       17       3916   66350  
11904          19       12       3916  128000  
11905          19       12       3916  130000  
11906          19       12       3916  131500  

[334 rows x 16 columns]

In [120]:
bmw_df.MSRP.values

array(['46135', '40650', '36350', '29450', '34500', '31200', '44100',
       '39300', '36900', '37200', '39600', '31500', '44400', '37200',
       '31500', '48250', '43550', '32850', '38650', '48750', '34850',
       '40650', '44150', '32850', '46150', '50750', '46450', '49050',
       '51050', '44450', '38950', '33150', '35150', '40950', '47250',
       '41850', '41850', '43000', '49200', '49650', '43950', '41950',
       '50150', '37500', '43750', '39000', '39500', '39500', '34950',
       '45750', '43450', '37500', '41000', '32950', '41850', '47800',
       '39850', '38350', '40350', '38350', '42650', '33150', '35150',
       '44150', '45800', '38750', '35450', '33450', '40750', '42250',
       '42950', '40250', '49900', '47900', '44450', '42300', '40300',
       '40300', '42300', '45800', '47800', '43650', '49950', '47950',
       '41650', '48300', '50300', '43950', '41950', '56900', '46250',
       '50750', '42750', '48750', '48250', '42750', '50750', '40750',
       '54900', '487

In [121]:
bmw_df['MSRP'] = pd.to_numeric(bmw_df['MSRP'].str.replace(",", ""), errors='coerce')
bmw_df.MSRP.mean()

/var/folders/hb/6ftrzv4d27l4qgry0h5tcc040000gn/T/ipykernel_54660/2351836503.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bmw_df['MSRP'] = pd.to_numeric(bmw_df['MSRP'].str.replace(",", ""), errors='coerce')


61546.76347305389